import { createTheme } from "@mui/material";
import { FontConstants } from "../constants/FontConstants";
import { getColor } from "../globalColors/Colors";

const theme = createTheme({
  spacing: 10,
  palette: {
    primary: {
      main: "#0F172A",
      light: "#f9f9f9",
      contrastText: "#5131a5",
      dark: "#312E81",
    },
    secondary: {
      main: "#e5e5e5",
      contrastText: "#818CF8",
      light: "#E0F2FE",
      dark: "#9c9ba9",
    },
    success: { main: "#ECFDF5", dark: "#059669" },
  },
  typography: {
    fontFamily: FontConstants.AppFont1,
    fontSize: 14,
    display_01_medium: {
      fontFamily: FontConstants.AppFont1,
      display: FontConstants.AppFont1,
      fontSize: "2.875rem",
      fontWeight: "bold",
    },
    display_01_bold: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "4.5rem",
      fontWeight: 700,
    },
    display_01_extra_bold: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "4.5rem",
      fontWeight: 800,
    },
    display_02_medium: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "3.75rem",
      fontWeight: 500,
    },
    display_02_bold: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "3.75rem",
      fontWeight: 700,
    },
    display_02_extra_bold: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "3.75rem",
      fontWeight: 800,
    },
    display_02_extra_bold_900: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "3.125rem",
      fontWeight: "bold",
    },
    display_03_extra_bold_900: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "5rem",
      fontWeight: 700,
      lineHeight: "4rem",
    },
    heading_01_medium: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "3rem",
      fontWeight: 500,
    },
    heading_01_bold: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "3rem",
      fontWeight: 700,
    },
    heading_01_extra_bold: {
      fontFamily: "Roboto",
      display: "block",
      fontSize: "3rem",
      fontWeight: 800,
    },
    heading_01_small: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1.875rem",
      fontWeight: 400,
    },
    heading_01_small_medium: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1.875rem",
      fontWeight: 600,
    },
    heading_01_small_bold: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1.875rem",
      fontWeight: 700,
    },
    heading_01_small_extra_bold: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1.875rem",
      fontWeight: 800,
    },
    heading_01_small_extra_bold_900: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1.875rem",
      fontWeight: "normal",
    },
    heading_02_medium: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1.5rem",
      fontWeight: 500,
    },
    heading_02_bold: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1.5rem",
      fontWeight: 700,
    },
    heading_02_extra_bold: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1.5rem",
      fontWeight: "bold",
    },
    heading_03_medium: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1.25rem",
      fontWeight: "bold",
    },
    heading_03_bold: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1.25rem",
      fontWeight: 700,
    },
    heading_03_extra_bold: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1.25rem",
      fontWeight: 300,
    },
    heading_03_extra_bold_900: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1.25rem",
      fontWeight: 900,
    },
    heading_04_medium: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1rem",
      fontWeight: 500,
    },
    heading_04_bold: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1rem",
      fontWeight: 700,
    },
    heading_04_extra_bold: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1rem",
      fontWeight: "600",
    },
    heading_05_light: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "0.875rem",
      fontWeight: 300,
      lineHeight: "1.05rem",
    },
    heading_05_medium: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "0.875rem",
      fontWeight: 600,
      lineHeight: "1.05rem",
    },
    heading_05_bold: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "0.875rem",
      fontWeight: 700,
    },
    heading_05_extra_bold: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "0.875rem",
      fontWeight: 800,
    },
    heading_06_medium: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "0.75rem",
      fontWeight: 500,
    },
    heading_06_bold: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1rem",
      fontWeight: "bold",
    },
    heading_06_extra_bold: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "0.75rem",
      fontWeight: 800,
    },
    heading_07_bold: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1.125rem",
      fontWeight: 600,
    },
    sub_heading_extra_small: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "0.75rem",
      fontWeight: 400,
    },
    sub_heading_small: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "0.875rem",
      fontWeight: 400,
    },
    sub_heading_small_2: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1.625rem",
      fontWeight: 700,
    },
    sub_heading_medium: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1rem",
      fontWeight: "600",
      color: "#334155",
    },
    sub_heading_bold: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1rem",
      fontWeight: 600,
    },
    sub_heading_2_extra_bold_900: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1rem",
      fontWeight: 900,
      textTransform: "uppercase",
      lineHeight: "1.2rem",
      textAlign: "center",
      color: getColor("primary", 200),
    },
    paragraph_01_medium: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1.5rem",
      fontWeight: 400,
    },
    paragraph_01_bold: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1.25rem",
      fontWeight: "normal",
    },
    paragraph_02_medium: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1rem",
      fontWeight: 400,
    },
    paragraph_02_bold: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1rem",
      fontWeight: 500,
    },
    paragraph_02_medium_font1: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "0.875rem",
      fontWeight: "normal",
      color: getColor("primary", 150),
      lineHeight: 1.71,
      textAlign: "center",
    },
    paragraph_02_medium_font2: {
      fontFamily: FontConstants.AppFont2,
      display: "block",
      fontSize: "1rem",
      fontWeight: 400,
      opacity: 0.5,
      color: getColor("primary", 0),
    },
    paragraph_03_medium: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "0.75rem",
      fontWeight: "normal",
    },
    paragraph_03_bold: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "0.75rem",
      fontWeight: 500,
    },
    paragraph_04_medium: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "1.125rem",
      fontWeight: "normal",
    },
    caption_regular: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "0.6875rem",
      fontWeight: 400,
    },
    caption_medium: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "0.6875rem",
      fontWeight: 500,
    },
    caption_uppercase: {
      fontFamily: FontConstants.AppFont1,
      display: "block",
      fontSize: "0.6875rem",
      fontWeight: 500,
      textTransform: "uppercase",
    },
    button_01_medium: {
      display: "block",
      fontSize: "1rem",
      fontWeight: "bold",
      lineHeight: 1.5,
      textTransform: "none",
    },
  },
});
export { theme };
